### ISSUE TITLE
If no schedules are active, need an error message

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#71] opened 2015-02-15 20:46 UTC
If no schedules are active, when you try to click the right arrow from the 'admin" screen at check-in nothing happens and you get no message.  Looks like the page is just stuck.

**Comment by dcs619** [comment] 2015-02-15 20:50
Duplicate of #68, modals aren't showing up.  There is already a modal there.

**Closed as completed by dcs619** 2015-02-15 20:50 UTC
